-- @description Seahorse Source-Destination Tools 
-- @version 0.1 
-- @author the soapy zoo
-- @about
--   # Seahorse Source-Destination Tools 
--   _documentation will follow soon(TM)_
-- @metapackage
-- @provides
--    [main] *.lua
--    [nomain] soapy-seahorse_functions\*.lua
--    [nomain] .
--    [nomain] *.md